const store = {
  game: {
    startTime: "2021-07-20T10:00:00.0000",
    bookmarks: [],
    rubberBands: 0,
    clothespins: 0,
    cockAndBallsBound: false,
    ruins: 0,
    edges: 0,
    orgasms: 0,
    strokeStyle: "dominant",
    buttPlugInserted: false,
    orgasm: false,
    youtube: null,
    cooldown: false,
  },
  config: {
    redditId:
      "NSFW_GIF, gonewild, nsfw, 60fpsporn, porninaminute, holdthemoan, cumsluts, realgirls, gwcouples, porninfifteenseconds, cuckold, hotwife, anal, blowjobs, bustypetite, ass, collegesluts, wifesharing, creampies, ruinedorgasms, chastitycouples, postorgasm",
    gifs: true,
    pictures: true,
    videos: true,
    slideDuration: 10,
    finalOrgasmAllowed: true,
    allowedProbability: 100,
    deniedProbability: 0,
    ruinedProbability: 0,
    minimumGameTime: 5,
    maximumGameTime: 20,
    minimumEdges: 0,
    minimumRuinedOrgasms: 0,
    maximumRuinedOrgasms: 0,
    maximumOrgasms: 1,
    postOrgasmTorture: false,
    postOrgasmTortureMinimumTime: 10,
    postOrgasmTortureMaximumTime: 90,
    edgeCooldown: 10,
    edgeFrequency: 0,
    ruinCooldown: 20,
    slowestStrokeSpeed: 0.25,
    fastestStrokeSpeed: 4,
    initialGripStrength: 3,
    defaultStrokeStyle: "dominant",
    actionFrequency: 30,
    tasks: {
      doubleStrokes: true,
      halvedStrokes: true,
      teasingStrokes: true,
      accelerationCycles: false,
      randomBeat: false,
      randomStrokeSpeed: false,
      redLightGreenLight: false,
      clusterStrokes: false,
      gripChallenge: false,
      dominant: true,
      nondominant: false,
      headOnly: false,
      shaftOnly: false,
      overhandGrip: false,
      bothHands: false,
      handsOff: false,
      gripAdjustments: true,
      bindCockBalls: false,
      rubberBands: false,
      ballSlaps: false,
      squeezeBalls: false,
      headPalming: false,
      icyHot: false,
      toothpaste: false,
      breathPlay: false,
      scratching: false,
      flicking: false,
      cbtIce: false,
      precum: false,
      buttplug: false,
      rubNipples: false,
      clothespins: false,
      nipplesAndStroke: false,
    },
  },
};

export default store;
