const store = {
  game: {
    startTime: "2021-07-20T10:00:00.0000",
    bookmarks: [],
    rubberBands: 0,
    clothespins: 0,
    cockAndBallsBound: false,
    ruins: 0,
    edges: 0,
    orgasms: 0,
    strokeStyle: "dominant",
    buttPlugInserted: false,
    orgasm: false,
    youtube: null,
    cooldown: false,
  },
  config: {
    subreddits: [
      "gonewild",
      "nsfw",
      "realgirls",
      "nsfw_gif",
      "cumsluts",
      "petitegonewild",
      "holdthemoan",
      "anal",
      "creampies",
    ],
    slideDuration: 10,
    imageType: ["PICTURE", "GIF", "VIDEO"],
    gameDuration: {
      min: 5,
      max: 20,
    },
    finaleProbabilities: {
      orgasm: 100,
      denied: 0,
      ruined: 0,
    },
    postOrgasmTorture: false,
    postOrgasmTortureDuration: {
      min: 10,
      max: 90,
    },
    ruinedOrgasms: {
      min: 0,
      max: 0,
    },
    edgeCooldown: 10,
    edgeFrequency: 0,
    ruinCooldown: 20,
    minimumEdges: 0,
    strokeSpeed: {
      min: 0.25,
      max: 4,
    },
    orgasms: {
      min: 1,
      max: 1,
    },
    initialGripStrength: 3,
    defaultStrokeStyle: "dominant",
    actionFrequency: 30,
    tasks: {
      doubleStrokes: true,
      halvedStrokes: true,
      teasingStrokes: true,
      accelerationCycles: false,
      randomBeat: false,
      randomStrokeSpeed: false,
      redLightGreenLight: false,
      clusterStrokes: false,
      gripChallenge: false,
      dominant: true,
      nondominant: false,
      headOnly: false,
      shaftOnly: false,
      overhandGrip: false,
      bothHands: false,
      handsOff: false,
      gripAdjustments: true,
      bindCockBalls: false,
      rubberBands: false,
      ballSlaps: false,
      squeezeBalls: false,
      headPalming: false,
      icyHot: false,
      toothpaste: false,
      breathPlay: false,
      scratching: false,
      flicking: false,
      cbtIce: false,
      clothespins: false,
      precum: false,
      buttplug: false,
      rubNipples: false,
      nipplesAndStroke: false,
    },
  },
};

export default store;
